// @ts-check
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import { remarkMermaid } from './src/lib/remark-mermaid.mjs';

import cloudflare from '@astrojs/cloudflare';

// https://astro.build/config
export default defineConfig({
  site: 'https://blog.mikepfunk.com',
  integrations: [mdx(), sitemap()],
  adapter: cloudflare({
    platformProxy: {
      enabled: true
    }
  }),
  markdown: {
    syntaxHighlight: {
      type: 'shiki',
      excludeLangs: ['mermaid'] // Exclude mermaid from syntax highlighting - Generated by Copilot
    },
    remarkPlugins: [remarkMermaid] // Convert ```mermaid to <pre class="mermaid"> - Generated by Copilot
  }
});